version: "3"
services:
  reverseproxy:
      image: plasmafrog/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: plasmafrog/udacity-c3-user-service
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_AWS_REGION: $POSTGRES_AWS_REGION
      POSTGRES_AWS_PROFILE: $POSTGRES_AWS_PROFILE
      POSTGRES_AWS_MEDIA_BUCKET: $POSTGRES_AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      PORT_FEED_SERVICE: $PORT_FEED_SERVICE
      PORT_USER_SERVICE: $PORT_USER_SERVICE
      URL: "http://localhost:8100"
  backend-feed:
    image: plasmafrog/udacity-c3-feed-service
    volumes: 
      - $HOME/.aws_udacity:/root/.aws # Mount local
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_AWS_REGION: $POSTGRES_AWS_REGION
      POSTGRES_AWS_PROFILE: $POSTGRES_AWS_PROFILE
      POSTGRES_AWS_MEDIA_BUCKET: $POSTGRES_AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      PORT_FEED_SERVICE: $PORT_FEED_SERVICE
      PORT_USER_SERVICE: $PORT_USER_SERVICE
      URL: "http://localhost:8100"
  frontend:
    image: plasmafrog/udacity-frontend
    ports:
      - "8100:80" # Exposed on 8100
